application: fourth-scheme-677
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /.*
  script: webapp.application
  
# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
#- name: healthvaultlib
#  version: latest
# [END libraries]